services:
  request-service-postgres:
    image: postgres:16-alpine
    container_name: dobrovichek-request-postgres
    environment:
      POSTGRES_DB: dobrovichek_request
      POSTGRES_USER: dobrovichek
      POSTGRES_PASSWORD: dobrovichek
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dobrovichek -d dobrovichek_request"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - request-service-postgres-data:/var/lib/postgresql/data

  user-service-postgres:
    image: postgres:16-alpine
    container_name: dobrovichek-user-postgres
    environment:
      POSTGRES_DB: dobrovichek_user
      POSTGRES_USER: dobrovichek
      POSTGRES_PASSWORD: dobrovichek
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dobrovichek -d dobrovichek_user"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: dobrovichek-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  request-service-postgres-data:
  user-service-postgres-data:
