spring:
  application:
    name: request-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:postgresql://${REQUEST_DB_HOST:localhost}:${REQUEST_DB_PORT:5433}/${REQUEST_DB_NAME:dobrovichek_request}
    username: ${REQUEST_DB_USERNAME:dobrovichek}
    password: ${REQUEST_DB_PASSWORD:dobrovichek}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match:
    - /api/v1/**

server:
  port: 8083

dobrovichek:
  messaging:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
