spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-auth
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
        - id: request-api
          uri: ${REQUEST_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/requests/**
        - id: user-api
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/users/**,/api/v1/volunteers/**

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info
